name: Release

on:
    pull_request:
        types: [closed]
        branches:
            - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node.js 22.x
              uses: actions/setup-node@v3
              with:
                  node-version: 22.x

            - name: Install Dependencies
              run: npm install

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Get New VSCode Extension changeset
              run: |
                  packages=$(echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -r '.[].name')

                  if echo "$packages" | grep -q "sqlanydb-tools-vscode"; then
                    echo "VSCODE_CHANGED=true" >> $GITHUB_ENV
                  else
                    echo "VSCODE_CHANGED=false" >> $GITHUB_ENV
                  fi

            - name: Debug
              run: |
                  echo ${{ env.VSCODE_CHANGED }}
                  echo ${{ steps.changesets.outputs.publishedPackages }}

            - name: Build and Publish VSCode Extension
              if: env.VSCODE_CHANGED == 'true'
              run: |
                  cd ./apps/sqlanydb-tools-vscode
                  npm run publish
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
