name: Release

on:
    pull_request:
        types: [closed]
        branches:
            - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node.js 22.x
              uses: actions/setup-node@v3
              with:
                  node-version: 22.x

            - name: Install Dependencies
              run: npm install

            - name: Debug Environment
              run: |
                  echo "Current Directory:"
                  pwd
                  echo "All Files:"
                  ls -la
                  echo "Contents of .changeset Directory:"
                  ls -la .changeset || echo "No .changeset directory found."

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Debug Environment
              run: |
                  echo "Current Directory:"
                  pwd
                  echo "All Files:"
                  ls -la
                  echo "Contents of .changeset Directory:"
                  ls -la .changeset || echo "No .changeset directory found."

            - name: Get New VSCode Extension changeset
              run: |
                  changeset_files=$(find .changeset -name '*.md')
                  found=false

                  for file in $changeset_files; do
                    if grep -q "sqlanydb-tools-vscode" "$file"; then
                      found=true
                      break
                    fi
                  done

                  if [ "$found" = true ]; then
                    echo "VSCODE_CHANGED=true" >> $GITHUB_ENV
                  else
                    echo "VSCODE_CHANGED=false" >> $GITHUB_ENV
                  fi

            - name: Build and Publish VSCode Extension
              if: env.VSCODE_CHANGED == 'true'
              run: |
                  cd ./apps/sqlanydb-tools-vscode
                  npm run publish
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
